<?php
/**
 * JSON Toolbox - Språkfil (sv/en)
 * Version: 1.0 - Sprint 1
 * 
 * Komplett i18n-stöd för alla flikar och funktioner
 */

require_once __DIR__ . '/../../includes/lang-helper.php';

$lang = getLang();

$translations = [
    'sv' => [
        // Meta & SEO
        'title' => 'JSON Toolbox - Komplett verktygslåda för JSON och datakonvertering',
        'meta_description' => 'Kraftfull JSON-verktygslåda: konvertera CSV, XML, YAML, formatera, validera, reparera och transformera JSON. 100% lokal processing - ingen data lämnar din webbläsare.',
        'keywords' => 'json toolbox, json converter, csv to json, xml to json, yaml to json, json formatter, json validator, json fixer, json diff, jsonpath, json schema, typescript interface',

        // Page content
        'h1' => 'JSON Toolbox',
        'lead' => 'Komplett verktygslåda för JSON och datakonvertering. Snabbt, säkert och helt lokalt i din webbläsare.',
        
        // Privacy indicator
        'privacy_badge' => 'All processing sker lokalt',
        'privacy_tooltip' => 'Ingen data skickas till servern. Fungerar offline.',
        
        // Tab names (clean, icons in HTML)
        'tab_csv' => 'CSV',
        'tab_css' => 'CSS',
        'tab_xml' => 'XML',
        'tab_yaml' => 'YAML',
        'tab_format' => 'Format',
        'tab_validate' => 'Validera',
        'tab_fix' => 'Reparera',
        'tab_diff' => 'Diff',
        'tab_query' => 'Query',
        'tab_schema' => 'Schema',
        'tab_transform' => 'Transform',
        'tab_utilities' => 'Verktyg',
        'tab_tree' => 'Trädvy',
        
        // Tab tooltips
        'tab_csv_tooltip' => 'Konvertera mellan CSV och JSON',
        'tab_css_tooltip' => 'Konvertera CSS till JSON',
        'tab_xml_tooltip' => 'Konvertera mellan XML och JSON',
        'tab_yaml_tooltip' => 'Konvertera mellan YAML och JSON',
        'tab_format_tooltip' => 'Formatera och minifiera JSON',
        'tab_validate_tooltip' => 'Validera JSON syntax och schema',
        'tab_fix_tooltip' => 'Reparera trasig JSON',
        'tab_diff_tooltip' => 'Jämför två JSON-objekt',
        'tab_query_tooltip' => 'Sök med JSONPath',
        'tab_schema_tooltip' => 'JSON Schema verktyg',
        'tab_transform_tooltip' => 'Generera TypeScript interfaces',
        'tab_utilities_tooltip' => 'URL encode, Base64, escape',
        'tab_tree_tooltip' => 'Visa JSON som interaktivt träd',
        
        // Tab groups (UX Layout Pass v1)
        'tab_group_convert' => 'Konvertera',
        'tab_group_format' => 'Formatera',
        'tab_group_analyze' => 'Analysera',
        'tab_group_generate' => 'Generera',
        
        // Tab icons (Lucide icon names)
        'tab_csv_icon' => 'table',
        'tab_css_icon' => 'paintbrush',
        'tab_xml_icon' => 'code',
        'tab_yaml_icon' => 'file-code',
        'tab_format_icon' => 'indent-increase',
        'tab_validate_icon' => 'check-circle',
        'tab_fix_icon' => 'wrench',
        'tab_diff_icon' => 'git-compare-arrows',
        'tab_query_icon' => 'search',
        'tab_schema_icon' => 'network',
        'tab_transform_icon' => 'shuffle',
        'tab_utilities_icon' => 'settings',
        'tab_tree_icon' => 'folder-tree',
        
        // Section titles (clean, no arrows)
        'section_csv' => 'CSV till JSON',
        'section_css' => 'CSS till JSON',
        'section_xml' => 'XML till JSON',
        'section_yaml' => 'YAML till JSON',
        'section_format' => 'JSON Formatering',
        'section_validate' => 'JSON Validering',
        'section_fix' => 'JSON Reparation',
        'section_diff' => 'JSON Diff',
        'section_query' => 'JSONPath Query',
        'section_schema' => 'JSON Schema',
        'section_transform' => 'Transform & Export',
        'section_utilities' => 'Verktyg',
        'section_tree' => 'Trädvy',
        
        // Common UI elements
        'input_label' => 'Input:',
        'output_label' => 'Output:',
        'copy' => 'Kopiera',
        'download' => 'Ladda ner',
        'clear' => 'Rensa',
        'paste' => 'Klistra in',
        'convert' => 'Konvertera',
        'swap' => 'Byt riktning',
        'send_to' => 'Skicka till',
        
        // Status messages
        'copied' => 'Kopierat!',
        'error' => 'Fel',
        'success' => 'Klart!',
        'processing' => 'Bearbetar...',
        'no_input' => 'Ingen input angiven.',
        
        // Placeholder text
        'placeholder_json' => 'Klistra in JSON här...',
        'placeholder_csv' => 'Klistra in CSV-data här...',
        'placeholder_xml' => 'Klistra in XML här...',
        'placeholder_yaml' => 'Klistra in YAML här...',
        'placeholder_css' => 'Klistra in CSS här...',
        
        // CSV Module
        'csv_hint' => 'Klistra in från Excel, dra en fil, eller skriv direkt',
        'csv_delimiter' => 'Avgränsare',
        'csv_auto_detect' => 'Auto-detect',
        'csv_comma' => 'Komma',
        'csv_tab' => 'Tab',
        'csv_semicolon' => 'Semikolon',
        'csv_pipe' => 'Pipe',
        'csv_first_row_header' => 'Första raden är rubrik',
        'csv_transpose' => 'Transponera (byt rader/kolumner)',
        'csv_select_columns' => 'Välj kolumner',
        'csv_select_all' => 'Välj alla',
        'csv_deselect_all' => 'Avmarkera alla',
        'csv_rows' => 'rader',
        'csv_pasted' => 'Klistrat in från urklipp',
        'csv_paste_error' => 'Kunde inte klistra in från urklipp',
        'csv_cleared' => 'Rensat',
        'csv_downloaded' => 'Nedladdat',
        'csv_file_error' => 'Kunde inte läsa fil',
        'csv_sent_to_format' => 'Skickat till Format-fliken',
        'csv_no_send_targets' => 'Inga giltiga mål för CSV-output',
        'csv_output_placeholder' => 'Konverterad output visas här...',
        'drop_file' => 'Släpp fil här',
        'no_output' => 'Ingen output att kopiera',
        
        // CSS Module
        'css_hint' => 'Klistra in CSS-kod eller dra en .css-fil',
        'css_minify_output' => 'Minifiera output',
        'css_include_comments' => 'Inkludera kommentarer',
        'css_flatten_media' => 'Platta ut @media-queries',
        'css_rules' => 'regler',
        'css_output_placeholder' => 'JSON-output visas här...',
        'css_pasted' => 'Klistrat in från urklipp',
        'css_sent_to_format' => 'Skickat till Format-fliken',
        
        // Format Module
        'format_presets' => 'Förval',
        'format_beautify' => 'Formatera',
        'format_minify' => 'Minifiera',
        'format_sorted' => 'Sorterade nycklar',
        'format_canonical' => 'Kanonisk',
        'format_indent' => 'Indrag',
        'format_spaces' => 'mellanslag',
        'format_tab' => 'Tab',
        'format_none' => 'Ingen (minifierad)',
        'format_sort_keys' => 'Sortera nycklar alfabetiskt',
        'format_escape_unicode' => 'Escape unicode-tecken',
        'format_apply' => 'Formatera',
        'format_output_placeholder' => 'Formaterad JSON visas här...',
        'sent_to_validate' => 'Skickat till Validera-fliken',
        'pasted' => 'Klistrat in från urklipp',
        'downloaded' => 'Nedladdat',
        'cleared' => 'Rensat',
        
        // Validate Module
        'validate_schema_optional' => 'JSON Schema (valfritt)',
        'validate_schema_placeholder' => 'Klistra in JSON Schema här för validering...',
        'validate_check' => 'Validera',
        'validate_valid' => 'Giltig JSON',
        'validate_invalid' => 'Ogiltig JSON',
        'validate_type' => 'Typ',
        'validate_items' => 'Element',
        'validate_keys' => 'Nycklar',
        'validate_depth' => 'Djup',
        'validate_size' => 'Storlek',
        'validate_line' => 'Rad',
        'validate_column' => 'Kolumn',
        'validate_schema_valid' => 'Schema-validering godkänd',
        'validate_send_to_fix' => 'Skicka till Reparera',
        'validate_success' => 'JSON är giltig!',
        'validate_error' => 'JSON-validering misslyckades',
        'sent_to_fix' => 'Skickat till Reparera-fliken',
        
        // Fix Module
        'fix_input_label' => 'Trasig JSON',
        'fix_placeholder' => 'Klistra in trasig JSON här...',
        'fix_can_fix' => 'Kan fixa',
        'fix_trailing_commas' => 'Efterföljande komman',
        'fix_single_quotes' => 'Enkla citattecken',
        'fix_unquoted_keys' => 'Ej citerade egenskapsnycklar',
        'fix_comments' => 'Kommentarer (// och /* */)',
        'fix_python' => 'Python True/False/None',
        'fix_newlines' => 'Radbrytningar i strängar',
        'fix_repair' => 'Reparera JSON',
        'fix_repaired' => 'Reparerad JSON',
        'fix_already_valid' => 'JSON är redan giltig!',
        'fix_no_repair_needed' => 'Ingen reparation behövs',
        'fix_success' => 'JSON reparerad!',
        'fix_failed' => 'Kunde inte reparera JSON',
        'fix_repaired_success' => 'JSON har reparerats',
        'fix_repair_failed' => 'Reparation misslyckades',
        'sent_to_format' => 'Skickat till Format-fliken',
        
        // XML Module
        'xml_compact' => 'Kompakt output',
        'xml_preserve_attributes' => 'Bevara attribut',
        'xml_trim' => 'Trimma whitespace',
        
        // YAML Module
        'yaml_indent' => 'Indrag',
        'yaml_flow_style' => 'Flow-stil (kompakt)',
        'yaml_no_refs' => 'Undvik YAML-referenser',
        
        // Diff Module
        'diff_left_label' => 'JSON A (Vänster)',
        'diff_right_label' => 'JSON B (Höger)',
        'diff_placeholder_left' => 'Klistra in första JSON här...',
        'diff_placeholder_right' => 'Klistra in andra JSON här...',
        'diff_compare' => 'Jämför',
        'diff_identical' => 'Identiska',
        'diff_differences' => 'Skillnader',
        'diff_added' => 'Tillagd',
        'diff_removed' => 'Borttagen',
        'diff_changed' => 'Ändrad',
        'diff_type_changed' => 'Typ ändrad',
        'diff_path' => 'Sökväg',
        'diff_left_value' => 'Värde A',
        'diff_right_value' => 'Värde B',
        'diff_no_differences' => 'Inga skillnader hittades',
        'diff_swap' => 'Byt A / B',
        'diff_ignore_order' => 'Ignorera array-ordning',
        'diff_ignore_whitespace' => 'Ignorera whitespace',
        'diff_clear_all' => 'Rensa allt',
        'diff_load_sample' => 'Ladda exempel',
        'diff_result' => 'Resultat',
        
        // Query Module
        'query_input_label' => 'JSON Data',
        'query_expression_label' => 'JSONPath Query',
        'query_placeholder' => 'Klistra in JSON här...',
        'query_expression_placeholder' => 't.ex. $.store.book[*].author',
        'query_execute' => 'Kör Query',
        'query_result' => 'Resultat',
        'query_matches' => 'träffar',
        'query_no_matches' => 'Inga träffar',
        'query_examples' => 'Exempel',
        'query_example_root' => 'Rot-element',
        'query_example_all' => 'Alla böcker',
        'query_example_first' => 'Första boken',
        'query_example_filter' => 'Filter pris < 10',
        'query_help' => 'JSONPath Hjälp',
        
        // Schema Module
        'schema_generate' => 'Generera Schema',
        'schema_validate' => 'Validera mot Schema',
        'schema_input_label' => 'JSON Data',
        'schema_output_label' => 'JSON Schema',
        'schema_placeholder' => 'Klistra in JSON för att generera schema...',
        'schema_output_placeholder' => 'Genererat schema visas här...',
        'schema_validation_input' => 'JSON att validera',
        'schema_infer_types' => 'Inferera typer strikt',
        'schema_required_all' => 'Alla fält required',
        'schema_additional_props' => 'Tillåt extra egenskaper',
        'schema_generated' => 'Schema genererat!',
        'schema_valid' => 'JSON matchar schema',
        'schema_invalid' => 'JSON matchar inte schema',
        'schema_errors' => 'Valideringsfel',
        
        // Transform Module
        'transform_input' => 'JSON Data',
        'transform_output' => 'Genererad kod',
        'transform_placeholder' => 'Klistra in JSON för att generera typer...',
        'transform_output_placeholder' => 'TypeScript/Go/Python kod visas här...',
        'transform_type' => 'Målformat',
        'transform_root_name' => 'Rotnamn',
        'transform_optional' => 'Valfria fält',
        'transform_export' => 'Exportera',
        'transform_generate' => 'Generera',
        'transform_success' => 'Kod genererad!',
        'load_sample' => 'Ladda exempel',
        'error_empty_input' => 'Ingen input angiven',
        'error_invalid_json' => 'Ogiltig JSON',
        'error_nothing_to_copy' => 'Inget att kopiera',
        'error_nothing_to_download' => 'Inget att ladda ner',
        'error_copy_failed' => 'Kopiering misslyckades',
        'error_paste_failed' => 'Inklistring misslyckades',
        
        // Utilities Module
        'utilities_input' => 'Input',
        'utilities_output' => 'Output',
        'utilities_placeholder' => 'Klistra in text här...',
        'utilities_output_placeholder' => 'Resultat visas här...',
        'utilities_swap' => 'Byt input/output',
        'utilities_url_encode' => 'URL Encode',
        'utilities_url_decode' => 'URL Decode',
        'utilities_url_encode_component' => 'Encode Component',
        'utilities_base64_encode' => 'Base64 Encode',
        'utilities_base64_decode' => 'Base64 Decode',
        'utilities_json_escape' => 'JSON Escape',
        'utilities_json_unescape' => 'JSON Unescape',
        'utilities_stringify' => 'Stringify',
        'utilities_html_encode' => 'HTML Encode',
        'utilities_html_decode' => 'HTML Decode',
        'utilities_unicode_escape' => 'Unicode Escape',
        'utilities_unicode_unescape' => 'Unicode Unescape',
        'utilities_text' => 'Text',
        'utilities_hash' => 'Hash',
        'utilities_hash_success' => 'Hash beräknad',
        'utilities_success' => 'Klart!',
        'utilities_unknown_action' => 'Okänd åtgärd',
        
        // Tree Module
        'tree_input' => 'JSON Data',
        'tree_placeholder' => 'Klistra in JSON här för trädvy...',
        'tree_view' => 'Trädvy',
        'tree_render' => 'Visa träd',
        'tree_expand_all' => 'Expandera alla',
        'tree_collapse_all' => 'Fäll ihop alla',
        'tree_search' => 'Sök i trädet...',
        'tree_empty' => 'Klistra in JSON och klicka "Visa träd"',
        'tree_render_success' => 'Trädvy genererad',
        'tree_objects' => 'objekt',
        'tree_arrays' => 'arrayer',
        'tree_primitives' => 'primitiver',
        'tree_path_hint' => 'Klicka på en nod för att se sökvägen',
        'tree_path_copied' => 'Sökväg kopierad!',
        'tree_copy_path' => 'Kopiera sökväg',
        
        // Direction toggles (i18n Pass v1)
        'direction_csv_to_json' => 'CSV till JSON',
        'direction_json_to_csv' => 'JSON till CSV',
        'direction_xml_to_json' => 'XML till JSON',
        'direction_json_to_xml' => 'JSON till XML',
        'direction_yaml_to_json' => 'YAML till JSON',
        'direction_json_to_yaml' => 'JSON till YAML',
        
        // Input/Output labels (i18n Pass v1)
        'label_csv_input' => 'CSV-indata',
        'label_csv_output' => 'CSV-utdata',
        'label_json_input' => 'JSON-indata',
        'label_json_output' => 'JSON-utdata',
        'label_xml_input' => 'XML-indata',
        'label_xml_output' => 'XML-utdata',
        'label_yaml_input' => 'YAML-indata',
        'label_yaml_output' => 'YAML-utdata',
        'label_css_input' => 'CSS-indata',
        
        // Stats messages (i18n Pass v1)
        'stats_rows_to_json' => 'rader till JSON',
        'stats_json_to_rows' => 'JSON till {n} rader',
        'stats_rules' => 'regler',
        
        // Error messages (i18n Pass v1)
        'error_must_be_array' => 'Indata måste vara en JSON-array eller objekt',
        'error_invalid_xml' => 'Ogiltig XML',
        'error_yaml_not_loaded' => 'js-yaml-biblioteket kunde inte laddas. Uppdatera sidan.',
        'error_no_matches' => 'Inga träffar',
        
        // Transform options (i18n Pass v1)
        'transform_typescript_interface' => 'TypeScript Interface',
        'transform_typescript_type' => 'TypeScript Type',
        'transform_jsdoc' => 'JSDoc typedef',
        'transform_go_struct' => 'Go Struct',
        'transform_python_dataclass' => 'Python dataclass',
        'transform_root_default' => 'RootObject',
        
        // File size units (i18n Pass v1)
        'unit_bytes' => 'B',
        'unit_kilobytes' => 'KB',
        'unit_megabytes' => 'MB',
        
        // Misc (i18n Pass v1)
        'path_root' => '(rot)',
        
        // Coming soon
        'coming_soon' => 'Kommer snart',
        'coming_soon_desc' => 'Denna funktion är under utveckling.',
        
        // Schema
        'schema_app_name' => 'JSON Toolbox',
        'schema_description' => 'Komplett verktygslåda för JSON och datakonvertering',
        
        // Keyboard shortcuts info
        'shortcuts_title' => 'Tangentbordsgenvägar',
        'shortcut_help' => 'Visa tangentbordsgenvägar',
        'shortcut_tabs' => 'Byt till flik 1-9',
        'shortcut_next_tab' => 'Nästa flik',
        'shortcut_prev_tab' => 'Föregående flik',
        'shortcut_run' => 'Kör aktuell operation',
        'shortcut_close' => 'Stäng modal/dialog',
        'shortcut_arrows' => 'Navigera flikar (när fokuserad)',
        'shortcut_hint' => 'Tryck ? när som helst för att visa/dölja denna hjälp',
        'shortcut_format' => 'Formatera',
        'shortcut_minify' => 'Minifiera',
        'shortcut_copy' => 'Kopiera output',
        'shortcut_paste' => 'Klistra in till input',
        'shortcut_group_navigation' => 'Navigering',
        'shortcut_group_actions' => 'Åtgärder',
        'shortcut_group_general' => 'Allmänt',
        
        // Status bar
        'status_mode' => 'Läge',
        'status_theme' => 'Tema',
        'status_theme_light' => 'Ljust',
        'status_theme_dark' => 'Mörkt',
        'status_lang' => 'Språk',
        'status_github' => 'Visa på GitHub',
        'status_output' => 'Output',
        'status_ready' => 'Redo',
        
        // Footer
        'clear_saved' => 'Rensa sparad data',
        'saved_cleared' => 'Sparad data rensad!',
        'shortcut_footer_hint' => 'Tryck ? för genvägar',
        
        // Readme link
        'readme_link' => 'Dokumentation & FAQ',
    ],
    'en' => [
        // Meta & SEO
        'title' => 'JSON Toolbox - Complete toolkit for JSON and data conversion',
        'meta_description' => 'Powerful JSON toolkit: convert CSV, XML, YAML, format, validate, repair and transform JSON. 100% local processing - no data leaves your browser.',
        'keywords' => 'json toolbox, json converter, csv to json, xml to json, yaml to json, json formatter, json validator, json fixer, json diff, jsonpath, json schema, typescript interface',

        // Page content
        'h1' => 'JSON Toolbox',
        'lead' => 'Complete toolkit for JSON and data conversion. Fast, secure and entirely local in your browser.',
        
        // Privacy indicator
        'privacy_badge' => 'All processing is local',
        'privacy_tooltip' => 'No data is sent to the server. Works offline.',
        
        // Tab names (clean, icons in HTML)
        'tab_csv' => 'CSV',
        'tab_css' => 'CSS',
        'tab_xml' => 'XML',
        'tab_yaml' => 'YAML',
        'tab_format' => 'Format',
        'tab_validate' => 'Validate',
        'tab_fix' => 'Fix',
        'tab_diff' => 'Diff',
        'tab_query' => 'Query',
        'tab_schema' => 'Schema',
        'tab_transform' => 'Transform',
        'tab_utilities' => 'Utilities',
        'tab_tree' => 'Tree View',
        
        // Tab tooltips
        'tab_csv_tooltip' => 'Convert between CSV and JSON',
        'tab_css_tooltip' => 'Convert CSS to JSON',
        'tab_xml_tooltip' => 'Convert between XML and JSON',
        'tab_yaml_tooltip' => 'Convert between YAML and JSON',
        'tab_format_tooltip' => 'Format and minify JSON',
        'tab_validate_tooltip' => 'Validate JSON syntax and schema',
        'tab_fix_tooltip' => 'Repair broken JSON',
        'tab_diff_tooltip' => 'Compare two JSON objects',
        'tab_query_tooltip' => 'Query with JSONPath',
        'tab_schema_tooltip' => 'JSON Schema tools',
        'tab_transform_tooltip' => 'Generate TypeScript interfaces',
        'tab_utilities_tooltip' => 'URL encode, Base64, escape',
        'tab_tree_tooltip' => 'View JSON as interactive tree',
        
        // Tab groups (UX Layout Pass v1)
        'tab_group_convert' => 'Convert',
        'tab_group_format' => 'Format',
        'tab_group_analyze' => 'Analyze',
        'tab_group_generate' => 'Generate',
        
        // Tab icons (Lucide icon names)
        'tab_csv_icon' => 'table',
        'tab_css_icon' => 'paintbrush',
        'tab_xml_icon' => 'code',
        'tab_yaml_icon' => 'file-code',
        'tab_format_icon' => 'indent-increase',
        'tab_validate_icon' => 'check-circle',
        'tab_fix_icon' => 'wrench',
        'tab_diff_icon' => 'git-compare-arrows',
        'tab_query_icon' => 'search',
        'tab_schema_icon' => 'network',
        'tab_transform_icon' => 'shuffle',
        'tab_utilities_icon' => 'settings',
        'tab_tree_icon' => 'folder-tree',
        
        // Section titles (clean, no arrows)
        'section_csv' => 'CSV to JSON',
        'section_css' => 'CSS to JSON',
        'section_xml' => 'XML to JSON',
        'section_yaml' => 'YAML to JSON',
        'section_format' => 'JSON Formatting',
        'section_validate' => 'JSON Validation',
        'section_fix' => 'JSON Repair',
        'section_diff' => 'JSON Diff',
        'section_query' => 'JSONPath Query',
        'section_schema' => 'JSON Schema',
        'section_transform' => 'Transform & Export',
        'section_utilities' => 'Utilities',
        'section_tree' => 'Tree View',
        
        // Common UI elements
        'input_label' => 'Input:',
        'output_label' => 'Output:',
        'copy' => 'Copy',
        'download' => 'Download',
        'clear' => 'Clear',
        'paste' => 'Paste',
        'convert' => 'Convert',
        'swap' => 'Swap direction',
        'send_to' => 'Send to',
        
        // Status messages
        'copied' => 'Copied!',
        'error' => 'Error',
        'success' => 'Done!',
        'processing' => 'Processing...',
        'no_input' => 'No input provided.',
        
        // Placeholder text
        'placeholder_json' => 'Paste JSON here...',
        'placeholder_csv' => 'Paste CSV data here...',
        'placeholder_xml' => 'Paste XML here...',
        'placeholder_yaml' => 'Paste YAML here...',
        'placeholder_css' => 'Paste CSS here...',
        
        // CSV Module
        'csv_hint' => 'Paste from Excel, drag a file, or type directly',
        'csv_delimiter' => 'Delimiter',
        'csv_auto_detect' => 'Auto-detect',
        'csv_comma' => 'Comma',
        'csv_tab' => 'Tab',
        'csv_semicolon' => 'Semicolon',
        'csv_pipe' => 'Pipe',
        'csv_first_row_header' => 'First row is header',
        'csv_transpose' => 'Transpose (swap rows/columns)',
        'csv_select_columns' => 'Select columns',
        'csv_select_all' => 'Select all',
        'csv_deselect_all' => 'Deselect all',
        'csv_rows' => 'rows',
        'csv_pasted' => 'Pasted from clipboard',
        'csv_paste_error' => 'Could not paste from clipboard',
        'csv_cleared' => 'Cleared',
        'csv_downloaded' => 'Downloaded',
        'csv_file_error' => 'Could not read file',
        'csv_sent_to_format' => 'Sent to Format tab',
        'csv_no_send_targets' => 'No valid targets for CSV output',
        'csv_output_placeholder' => 'Converted output will appear here...',
        'drop_file' => 'Drop file here',
        'no_output' => 'No output to copy',
        
        // CSS Module
        'css_hint' => 'Paste CSS code or drag a .css file',
        'css_minify_output' => 'Minify output',
        'css_include_comments' => 'Include comments',
        'css_flatten_media' => 'Flatten @media queries',
        'css_rules' => 'rules',
        'css_output_placeholder' => 'JSON output will appear here...',
        'css_pasted' => 'Pasted from clipboard',
        'css_sent_to_format' => 'Sent to Format tab',
        
        // Format Module
        'format_presets' => 'Presets',
        'format_beautify' => 'Beautify',
        'format_minify' => 'Minify',
        'format_sorted' => 'Sorted Keys',
        'format_canonical' => 'Canonical',
        'format_indent' => 'Indentation',
        'format_spaces' => 'spaces',
        'format_tab' => 'Tab',
        'format_none' => 'None (minified)',
        'format_sort_keys' => 'Sort keys alphabetically',
        'format_escape_unicode' => 'Escape unicode characters',
        'format_apply' => 'Format',
        'format_output_placeholder' => 'Formatted JSON will appear here...',
        'sent_to_validate' => 'Sent to Validate tab',
        'pasted' => 'Pasted from clipboard',
        'downloaded' => 'Downloaded',
        'cleared' => 'Cleared',
        
        // Validate Module
        'validate_schema_optional' => 'JSON Schema (optional)',
        'validate_schema_placeholder' => 'Paste JSON Schema here for validation...',
        'validate_check' => 'Validate',
        'validate_valid' => 'Valid JSON',
        'validate_invalid' => 'Invalid JSON',
        'validate_type' => 'Type',
        'validate_items' => 'Items',
        'validate_keys' => 'Keys',
        'validate_depth' => 'Depth',
        'validate_size' => 'Size',
        'validate_line' => 'Line',
        'validate_column' => 'Column',
        'validate_schema_valid' => 'Schema validation passed',
        'validate_send_to_fix' => 'Send to Fix',
        'validate_success' => 'JSON is valid!',
        'validate_error' => 'JSON validation failed',
        'sent_to_fix' => 'Sent to Fix tab',
        
        // Fix Module
        'fix_input_label' => 'Broken JSON',
        'fix_placeholder' => 'Paste broken JSON here...',
        'fix_can_fix' => 'Can fix',
        'fix_trailing_commas' => 'Trailing commas',
        'fix_single_quotes' => 'Single quotes',
        'fix_unquoted_keys' => 'Unquoted property keys',
        'fix_comments' => 'Comments (// and /* */)',
        'fix_python' => 'Python True/False/None',
        'fix_newlines' => 'Newlines in strings',
        'fix_repair' => 'Repair JSON',
        'fix_repaired' => 'Repaired JSON',
        'fix_already_valid' => 'JSON is already valid!',
        'fix_no_repair_needed' => 'No repair needed',
        'fix_success' => 'JSON repaired!',
        'fix_failed' => 'Could not repair JSON',
        'fix_repaired_success' => 'JSON has been repaired',
        'fix_repair_failed' => 'Repair failed',
        'sent_to_format' => 'Sent to Format tab',
        
        // XML Module
        'xml_compact' => 'Compact output',
        'xml_preserve_attributes' => 'Preserve attributes',
        'xml_trim' => 'Trim whitespace',
        
        // YAML Module
        'yaml_indent' => 'Indent',
        'yaml_flow_style' => 'Flow style (compact)',
        'yaml_no_refs' => 'Avoid YAML references',
        
        // Diff Module
        'diff_left_label' => 'JSON A (Left)',
        'diff_right_label' => 'JSON B (Right)',
        'diff_placeholder_left' => 'Paste first JSON here...',
        'diff_placeholder_right' => 'Paste second JSON here...',
        'diff_compare' => 'Compare',
        'diff_identical' => 'Identical',
        'diff_differences' => 'Differences',
        'diff_added' => 'Added',
        'diff_removed' => 'Removed',
        'diff_changed' => 'Changed',
        'diff_type_changed' => 'Type changed',
        'diff_path' => 'Path',
        'diff_left_value' => 'Value A',
        'diff_right_value' => 'Value B',
        'diff_no_differences' => 'No differences found',
        'diff_swap' => 'Swap A / B',
        'diff_ignore_order' => 'Ignore array order',
        'diff_ignore_whitespace' => 'Ignore whitespace',
        'diff_clear_all' => 'Clear all',
        'diff_load_sample' => 'Load sample',
        'diff_result' => 'Result',
        
        // Query Module
        'query_input_label' => 'JSON Data',
        'query_expression_label' => 'JSONPath Query',
        'query_placeholder' => 'Paste JSON here...',
        'query_expression_placeholder' => 'e.g. $.store.book[*].author',
        'query_execute' => 'Run Query',
        'query_result' => 'Result',
        'query_matches' => 'matches',
        'query_no_matches' => 'No matches',
        'query_examples' => 'Examples',
        'query_example_root' => 'Root element',
        'query_example_all' => 'All books',
        'query_example_first' => 'First book',
        'query_example_filter' => 'Filter price < 10',
        'query_help' => 'JSONPath Help',
        
        // Schema Module
        'schema_generate' => 'Generate Schema',
        'schema_validate' => 'Validate against Schema',
        'schema_input_label' => 'JSON Data',
        'schema_output_label' => 'JSON Schema',
        'schema_placeholder' => 'Paste JSON to generate schema...',
        'schema_output_placeholder' => 'Generated schema will appear here...',
        'schema_validation_input' => 'JSON to validate',
        'schema_infer_types' => 'Infer types strictly',
        'schema_required_all' => 'All fields required',
        'schema_additional_props' => 'Allow additional properties',
        'schema_generated' => 'Schema generated!',
        'schema_valid' => 'JSON matches schema',
        'schema_invalid' => 'JSON does not match schema',
        'schema_errors' => 'Validation errors',
        
        // Transform Module
        'transform_input' => 'JSON Data',
        'transform_output' => 'Generated code',
        'transform_placeholder' => 'Paste JSON to generate types...',
        'transform_output_placeholder' => 'TypeScript/Go/Python code will appear here...',
        'transform_type' => 'Target format',
        'transform_root_name' => 'Root name',
        'transform_optional' => 'Optional fields',
        'transform_export' => 'Export',
        'transform_generate' => 'Generate',
        'transform_success' => 'Code generated!',
        'load_sample' => 'Load sample',
        'error_empty_input' => 'No input provided',
        'error_invalid_json' => 'Invalid JSON',
        'error_nothing_to_copy' => 'Nothing to copy',
        'error_nothing_to_download' => 'Nothing to download',
        'error_copy_failed' => 'Copy failed',
        'error_paste_failed' => 'Paste failed',
        
        // Utilities Module
        'utilities_input' => 'Input',
        'utilities_output' => 'Output',
        'utilities_placeholder' => 'Paste text here...',
        'utilities_output_placeholder' => 'Result will appear here...',
        'utilities_swap' => 'Swap input/output',
        'utilities_url_encode' => 'URL Encode',
        'utilities_url_decode' => 'URL Decode',
        'utilities_url_encode_component' => 'Encode Component',
        'utilities_base64_encode' => 'Base64 Encode',
        'utilities_base64_decode' => 'Base64 Decode',
        'utilities_json_escape' => 'JSON Escape',
        'utilities_json_unescape' => 'JSON Unescape',
        'utilities_stringify' => 'Stringify',
        'utilities_html_encode' => 'HTML Encode',
        'utilities_html_decode' => 'HTML Decode',
        'utilities_unicode_escape' => 'Unicode Escape',
        'utilities_unicode_unescape' => 'Unicode Unescape',
        'utilities_text' => 'Text',
        'utilities_hash' => 'Hash',
        'utilities_hash_success' => 'Hash calculated',
        'utilities_success' => 'Done!',
        'utilities_unknown_action' => 'Unknown action',
        
        // Tree Module
        'tree_input' => 'JSON Data',
        'tree_placeholder' => 'Paste JSON here for tree view...',
        'tree_view' => 'Tree View',
        'tree_render' => 'Show tree',
        'tree_expand_all' => 'Expand all',
        'tree_collapse_all' => 'Collapse all',
        'tree_search' => 'Search in tree...',
        'tree_empty' => 'Paste JSON and click "Show tree"',
        'tree_render_success' => 'Tree view generated',
        'tree_objects' => 'objects',
        'tree_arrays' => 'arrays',
        'tree_primitives' => 'primitives',
        'tree_path_hint' => 'Click a node to see its path',
        'tree_path_copied' => 'Path copied!',
        'tree_copy_path' => 'Copy path',
        
        // Direction toggles (i18n Pass v1)
        'direction_csv_to_json' => 'CSV to JSON',
        'direction_json_to_csv' => 'JSON to CSV',
        'direction_xml_to_json' => 'XML to JSON',
        'direction_json_to_xml' => 'JSON to XML',
        'direction_yaml_to_json' => 'YAML to JSON',
        'direction_json_to_yaml' => 'JSON to YAML',
        
        // Input/Output labels (i18n Pass v1)
        'label_csv_input' => 'CSV Input',
        'label_csv_output' => 'CSV Output',
        'label_json_input' => 'JSON Input',
        'label_json_output' => 'JSON Output',
        'label_xml_input' => 'XML Input',
        'label_xml_output' => 'XML Output',
        'label_yaml_input' => 'YAML Input',
        'label_yaml_output' => 'YAML Output',
        'label_css_input' => 'CSS Input',
        
        // Stats messages (i18n Pass v1)
        'stats_rows_to_json' => 'rows to JSON',
        'stats_json_to_rows' => 'JSON to {n} rows',
        'stats_rules' => 'rules',
        
        // Error messages (i18n Pass v1)
        'error_must_be_array' => 'Input must be a JSON array or object',
        'error_invalid_xml' => 'Invalid XML',
        'error_yaml_not_loaded' => 'js-yaml library not loaded. Please refresh the page.',
        'error_no_matches' => 'No matches',
        
        // Transform options (i18n Pass v1)
        'transform_typescript_interface' => 'TypeScript Interface',
        'transform_typescript_type' => 'TypeScript Type',
        'transform_jsdoc' => 'JSDoc typedef',
        'transform_go_struct' => 'Go Struct',
        'transform_python_dataclass' => 'Python dataclass',
        'transform_root_default' => 'RootObject',
        
        // File size units (i18n Pass v1)
        'unit_bytes' => 'B',
        'unit_kilobytes' => 'KB',
        'unit_megabytes' => 'MB',
        
        // Misc (i18n Pass v1)
        'path_root' => '(root)',
        
        // Coming soon
        'coming_soon' => 'Coming soon',
        'coming_soon_desc' => 'This feature is under development.',
        
        // Schema
        'schema_app_name' => 'JSON Toolbox',
        'schema_description' => 'Complete toolkit for JSON and data conversion',
        
        // Keyboard shortcuts info
        'shortcuts_title' => 'Keyboard Shortcuts',
        'shortcut_help' => 'Show keyboard shortcuts',
        'shortcut_tabs' => 'Switch to tab 1-9',
        'shortcut_next_tab' => 'Next tab',
        'shortcut_prev_tab' => 'Previous tab',
        'shortcut_run' => 'Run current operation',
        'shortcut_close' => 'Close modal/dialog',
        'shortcut_arrows' => 'Navigate tabs (when focused)',
        'shortcut_hint' => 'Press ? anytime to toggle this help',
        'shortcut_format' => 'Format',
        'shortcut_minify' => 'Minify',
        'shortcut_copy' => 'Copy output',
        'shortcut_paste' => 'Paste to input',
        'shortcut_group_navigation' => 'Navigation',
        'shortcut_group_actions' => 'Actions',
        'shortcut_group_general' => 'General',
        
        // Status bar
        'status_mode' => 'Mode',
        'status_theme' => 'Theme',
        'status_theme_light' => 'Light',
        'status_theme_dark' => 'Dark',
        'status_lang' => 'Language',
        'status_github' => 'View on GitHub',
        'status_output' => 'Output',
        'status_ready' => 'Ready',
        
        // Footer
        'clear_saved' => 'Clear saved data',
        'saved_cleared' => 'Saved data cleared!',
        'shortcut_footer_hint' => 'Press ? for shortcuts',
        
        // Readme link
        'readme_link' => 'Documentation & FAQ',
    ]
];
